application:
  authentication:
    access_token:
      jwt_secretZ: 8GJ64eimY
      life_time: 3600000
    refresh_token:
      jwt_secret: Z8GJ64eimY
      life_time: 3600000



#application.authentication.access_token.jwt_secret:Z8GJ64eimY
#application.authentication.access_token.life_time: 3600000
#application.authentication.refresh_token.jwt_secret:Z8GJ64eimY
#application.authentication.refresh_token.life_time:3600000
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=okrs_authen
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.data.redis.port=6379
#spring.data.redis.host=localhost

# EUREKA CONFIG
server:
  port: 9091
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instanceId:myhost:myappname:9091


#Gateway config
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: verify-application
          uri: lb://user-service:8088
          predicates:
            - Path=/api/v1/users

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=okrs_authen
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true